105 in memory lock service
connext/vector pull request #109
Opened 2020-10-21 18:32 UTC by rhlsthrm

## The Problem

- Need to operate server node in single-container mode.

## The Solution

Fixes #105

2020-10-21 19:14 UTC, ArjunBhuptani approved these changes

2020-10-22 05:20 UTC, LayneHaber approved these changes
Wow that was quite the narrow race condition wasn't it

2020-10-22 05:21 UTC, LayneHaber requested changes
Do docs need to be updated now that we aren't always running redis?

2020-10-22 06:46 UTC, rhlsthrm commented
> Do docs need to be updated now that we aren't always running redis?

Yes, this is correct but ops are not updated yet, that will be done in a separate PR.

2020-10-22 06:50 UTC, merged