117 iterable mapping
connext/vector pull request #125
Opened 2020-10-26 16:36 UTC by LayneHaber

## The Problem
Fixes #117 

## The Solution
See changelog

2020-10-26 16:50 UTC, rhlsthrm requested changes

2020-10-26 16:50 UTC, rhlsthrm commented on modules/contracts/src.ts/tests/lib/iterableMapping.spec.ts
> +describe.only("LibIterableMapping.sol", () => {
Remove .only.

2020-10-26 17:41 UTC, HeikoFisch commented on modules/contracts/src.ts/tests/lib/iterableMapping.spec.ts
> +describe.only("LibIterableMapping.sol", () => {
Removed.

2020-10-27 09:18 UTC, bohendo approved these changes
Looks great

2020-10-27 09:18 UTC, merged