vector contracts deployed on maticmumbai
connext/vector pull request #150
Opened 2020-11-08 18:52 UTC by Aveesh52

## The Problem

## The Solution

2020-11-11 03:30 UTC, LayneHaber approved these changes

2020-11-11 03:32 UTC, LayneHaber requested changes
Looks great, but we've merged some contract changes from the time this contract was submitted, can you redeploy?

2020-11-12 01:32 UTC, rhlsthrm commented
Hey @Aveesh52, we redeployed to Matic with the latest contracts. The address book is updated in `main`. Closing this.

2020-11-12 01:32 UTC, closed without merging

2020-12-03 08:12 UTC, Aveesh52 commented
Okay